server:
  port: ${random.int[80800,80090]}
  
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
